# Generated by Django 6.0.6 on 2026-06-07 03:52

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已下架')], default='published', max_length=20)),
                ('cover_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=secrets.token_hex, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('dynasty', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='api.exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='GuideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=120)),
                ('route_description', models.TextField()),
                ('text_guide', models.TextField()),
                ('map_image_url', models.URLField(blank=True)),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='api.exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='MuseumActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('activity_time', models.DateTimeField()),
                ('location', models.CharField(max_length=120)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('published', '开放报名'), ('closed', '已下架/截止'), ('draft', '草稿')], default='published', max_length=20)),
                ('cover_image_url', models.URLField(blank=True)),
                ('volunteers', models.ManyToManyField(blank=True, related_name='assigned_activities', through='api.ActivityVolunteer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activityvolunteer',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.museumactivity'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('visitor', '游客'), ('admin', '管理员'), ('volunteer', '志愿者/讲解员')], default='visitor', max_length=20)),
                ('real_name', models.CharField(blank=True, max_length=80)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('service_area', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(max_length=60)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', '可预约'), ('closed', '已关闭')], default='open', max_length=20)),
            ],
            options={
                'ordering': ['visit_date', 'time_slot'],
                'unique_together': {('visit_date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '已预约'), ('cancelled', '已取消'), ('expired', '已过期')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.visitslot')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activityvolunteer',
            unique_together={('activity', 'volunteer')},
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', '已报名'), ('cancelled', '已取消')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.museumactivity')),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
