# Generated by Django 4.2.30 on 2026-06-16 17:14

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=api.models.default_auth_token_expires_at),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'slot')},
        ),
    ]
