# Generated by Django 4.2.30 on 2026-06-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_authtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="museumactivity",
            name="category",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="museumactivity",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="museumactivity",
            name="materials",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="museumactivity",
            name="preparation_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="museumactivity",
            name="target_audience",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
