# Generated by Django 4.2.30 on 2026-06-18 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_museumactivity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityvolunteer',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activityvolunteer',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='approved', max_length=20),
        ),
    ]
